  {MAIN_TOKEN, "bs (statement bs (';'/!.) bs)* !.", FILTER_AST_KEEP},
  {QUOTES_TOKEN, ""'" ('\\'. / !'\\'!"'". / "''")* "'" !"'"/ '"' ('\\'. / !'\\'!'"'. / "\"\"")* '"' !'"'", FILTER_AST_KEEP},
  {BS_TOKEN, "space*", FILTER_AST_DISCARD},
  {SPACE_TOKEN, "' ' / '\t' / '\n' / '\r' / '\v' / '\f' / comment", FILTER_AST_KEEP},
  {COMMENT_TOKEN, ""--" (!'\n'.)* ('\n'/!.)/ "/*" (!"*/".)* "*/"", FILTER_AST_KEEP},
  {STATEMENT_TOKEN, "begin_statement / insert_statement / start_statement / commit_statement", FILTER_AST_KEEP},
  {BEGIN_STATEMENT_TOKEN, "begin_kw bs work_kw?", FILTER_AST_KEEP},
  {INSERT_STATEMENT_TOKEN, "insert_kw bs (into_kw bs)? tbl_name bs( '(' bs (col_name bs (',' bs col_name bs)*)? ')' bs )? values_kw bs'(' expr bs (','bs expr bs)* ')' (','bs '(' expr bs (','bs expr bs)* ')')*", FILTER_AST_KEEP},
  {START_STATEMENT_TOKEN, "start_kw bs transaction_kw", FILTER_AST_KEEP},
  {COMMIT_STATEMENT_TOKEN, "commit_kw bs work_kw?", FILTER_AST_KEEP},
  {ALL_KW_TOKEN, "('A'/'a')('L'/'l')('L'/'l')!ident_char", FILTER_AST_KEEP},
  {AS_KW_TOKEN, "('A'/'a')('S'/'s')!ident_char", FILTER_AST_KEEP},
  {ASC_KW_TOKEN, "('A'/'a')('S'/'s')('C'/'c')!ident_char", FILTER_AST_KEEP},
  {AUTHORS_KW_TOKEN, "('A'/'a')('U'/'u')('T'/'t')('H'/'h')('O'/'o')('R'/'r')('S'/'s')!ident_char", FILTER_AST_KEEP},
  {BINARY_KW_TOKEN, "('B'/'b')('I'/'i')('N'/'n')('A'/'a')('R'/'r')('Y'/'y')!ident_char", FILTER_AST_KEEP},
  {BY_KW_TOKEN, "('B'/'b')('Y'/'y')!ident_char", FILTER_AST_KEEP},
  {COMMIT_KW_TOKEN, "('C'/'c')('O'/'o')('M'/'m')('M'/'m')('I'/'i')('T'/'t')!ident_char", FILTER_AST_KEEP},
  {CREATE_KW_TOKEN, "('C'/'c')('R'/'r')('E'/'e')('A'/'a')('T'/'t')('E'/'e')!ident_char", FILTER_AST_KEEP},
  {DESC_KW_TOKEN, "('D'/'d')('E'/'e')('S'/'s')('C'/'c')!ident_char", FILTER_AST_KEEP},
  {DISTINCT_KW_TOKEN, "('D'/'d')('I'/'i')('S'/'s')('T'/'t')('I'/'i')('N'/'n')('C'/'c')('T'/'t')!ident_char", FILTER_AST_KEEP},
  {FROM_KW_TOKEN, "('F'/'f')('R'/'r')('O'/'o')('M'/'m')!ident_char", FILTER_AST_KEEP},
  {GROUP_KW_TOKEN, "('G'/'g')('R'/'r')('O'/'o')('U'/'u')('P'/'p')!ident_char", FILTER_AST_KEEP},
  {HAVING_KW_TOKEN, "('H'/'h')('A'/'a')('V'/'v')('I'/'i')('N'/'n')('G'/'g')!ident_char", FILTER_AST_KEEP},
  {INSERT_KW_TOKEN, "('I'/'i')('N'/'n')('S'/'s')('E'/'e')('R'/'r')('T'/'t')!ident_char", FILTER_AST_KEEP},
  {INTO_KW_TOKEN, "('I'/'i')('N'/'n')('T'/'t')('O'/'o')!ident_char", FILTER_AST_KEEP},
  {LIMIT_KW_TOKEN, "('L'/'l')('I'/'i')('M'/'m')('I'/'i')('T'/'t')!ident_char", FILTER_AST_KEEP},
  {LOCAL_KW_TOKEN, "('L'/'l')('O'/'o')('C'/'c')('A'/'a')('L'/'l')!ident_char", FILTER_AST_KEEP},
  {LOCK_KW_TOKEN, "('L'/'l')('O'/'o')('C'/'c')('K'/'k')!ident_char", FILTER_AST_KEEP},
  {LOW_KW_TOKEN, "('L'/'l')('O'/'o')('W'/'w')!ident_char", FILTER_AST_KEEP},
  {OFFSET_KW_TOKEN, "('O'/'o')('F'/'f')('F'/'f')('S'/'s')('E'/'e')('T'/'t')!ident_char", FILTER_AST_KEEP},
  {ORDER_KW_TOKEN, "('O'/'o')('R'/'r')('D'/'d')('E'/'e')('R'/'r')!ident_char", FILTER_AST_KEEP},
  {READ_KW_TOKEN, "('R'/'r')('E'/'e')('A'/'a')('D'/'d')!ident_char", FILTER_AST_KEEP},
  {SELECT_KW_TOKEN, "('S'/'s')('E'/'e')('L'/'l')('E'/'e')('C'/'c')('T'/'t')!ident_char", FILTER_AST_KEEP},
  {SHOW_KW_TOKEN, "('S'/'s')('H'/'h')('O'/'o')('W'/'w')!ident_char", FILTER_AST_KEEP},
  {TABLE_KW_TOKEN, "('T'/'t')('A'/'a')('B'/'b')('L'/'l')('E'/'e')!ident_char", FILTER_AST_KEEP},
  {TABLES_KW_TOKEN, "('T'/'t')('A'/'a')('B'/'b')('L'/'l')('E'/'e')('S'/'s')!ident_char", FILTER_AST_KEEP},
  {TEMPORARY_KW_TOKEN, "('T'/'t')('E'/'e')('M'/'m')('P'/'p')('O'/'o')('R'/'r')('A'/'a')('R'/'r')('Y'/'y')!ident_char", FILTER_AST_KEEP},
  {UNLOCK_KW_TOKEN, "('U'/'u')('N'/'n')('L'/'l')('O'/'o')('C'/'c')('K'/'k')!ident_char", FILTER_AST_KEEP},
  {VALUES_KW_TOKEN, "('V'/'v')('A'/'a')('L'/'l')('U'/'u')('E'/'e')('S'/'s')!ident_char", FILTER_AST_KEEP},
  {WHERE_KW_TOKEN, "('W'/'w')('H'/'h')('E'/'e')('R'/'r')('E'/'e')!ident_char", FILTER_AST_KEEP},
  {WORK_KW_TOKEN, "('W'/'w')('O'/'o')('R'/'r')('K'/'k')!ident_char", FILTER_AST_KEEP},
  {WRITE_KW_TOKEN, "('W'/'w')('R'/'r')('I'/'i')('T'/'t')('E'/'e')!ident_char", FILTER_AST_KEEP},
  {SET_KW_TOKEN, "('S'/'s')('E'/'e')('T'/'t')!ident_char", FILTER_AST_KEEP},
  {UPDATE_KW_TOKEN, "('U'/'u')('P'/'p')('D'/'d')('A'/'a')('T'/'t')('E'/'e')!ident_char", FILTER_AST_KEEP},
  {WHERE_KW_TOKEN, "('W'/'w')('H'/'h')('E'/'e')('R'/'r')('E'/'e')!ident_char", FILTER_AST_KEEP},
  {TBL_NAME_TOKEN, "identifier", FILTER_AST_KEEP},
  {IDENTIFIER_TOKEN, "ident_char* !ident_char / '`' (!'`'. | "``")* '`'", FILTER_AST_KEEP},
  {IDENT_CHAR_TOKEN, "'A'..'Z'/'a'..'z'/'0'..'9'/'_'", FILTER_AST_KEEP},
